import Head from 'next/head';

import Header from '../components/Header';
import Homepage from '../components/HomePage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Poke Maker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Homepage />
      </main>
    </>
  )
}
